### ISSUE TITLE
Add a setting for lower process priority for ffmpeg

### ISSUE THREAD

**Issue by Darkle** [qtlmovie/qtlmovie#3]
When using qtlmovie to create a dvd, I often encounter slowness with other programs (e.g. chrome). Usually I use a task manager program to lower the priority of the ffmpeg process that qtlmovie is using to convert the video, but it would be great if qtlmovie had a setting built in where you could specify that it runs ffmpeg on a lower process priority automatically.

Details:
Running Windows 10 and using qtlmovie 1.10

Thanks for the program, I use it often.

**Comment by lelegard** [comment]
Excellent suggestion. It will be implemented in the next version.
Thank you for your feedback, much appreciated.

Implementation notes / reminder:
- Unix: reimplement QProcess::setupChildProcess
- Windows: use QProcess::setCreateProcessArgumentsModifier

**Comment by lelegard** [comment]
Implemented in commit bcce7d52cf4eb1038d801f30832b54b2b6c4ea4b

Test binaries are available for [Win64](https://sourceforge.net/projects/qtlmovie/files/test/QtlMovie-Win64-1.11-rc1.exe/download) and [Win32](https://sourceforge.net/projects/qtlmovie/files/test/QtlMovie-Win32-1.11-rc1.exe/download).

@Darkle Could you please try one of those binaries and see if it matches your expectations? Waiting for your feedback to close this issue.

**Comment by Darkle** [comment]
That worked fine. I didn't notice any slowness. Thanks.

**Comment by lelegard** [comment]
Thanks for your prompt feedback. Closing this issue.
