### ISSUE TITLE
TNT France DVB subtitles

### ISSUE THREAD

**Issue by pleiade67** [qtlmovie/qtlmovie#6]
Merci pour cet excellent logiciel (le seul à décoder correctement les sous-titres en teletext !).
J'ai un problème avec les enregistrements de la TNT HD française sur un récepteur CGV ETIMO T2 REC (Flux TS, H264, sous-titres en DVB).
Le transcodage ne démarre pas si on sélectionne l'un des sous-titres :
"Ce type de sous-titres ne peut pas être extrait par FFmpeg"
(problème reproduit sur un enregistrement TF1 et FR3).
Fichier log :
[debug] Recherche de sous-titres Teletext terminée
[debug] File: /Volumes/USB 128G/ALIDVRS2/[TS]2017-04-02.20.51.09-TF1-84/000.ts
[debug] Stream Mode: Transport Stream
[debug] Program Count: 5
[debug] Program Numbers: 1537 1538 1542 1544 1545 
[debug] PID: 120, Program: 1537, H.264 video
[debug] PID: 130, Program: 1537, MPEG-2 private data
[debug] PID: 131, Program: 1537, MPEG-2 private data
[debug] PID: 132, Program: 1537, MPEG-2 private data
[debug] PID: 150, Program: 1537, DVB Subtitles
[debug] PID: 151, Program: 1537, DVB Subtitles
[debug] PID: 170, Program: 1537, MPEG-2 private table sections
[debug] //////// Program #1537: ////////
[debug] DVB Subtitles: No
[debug] Teletext: No
[debug] ATSC Closed Caption: Yes
[debug] EIA-608: No
[debug] CEA-708: No
[debug] MPEG-4 Timed Text: No
[debug] Fin de recherche des Closed Captions
[debug] CCExtractor terminé avec le code 0
.
Ce type de sous-titres ne peut pas être extrait par FFmpeg
Opération terminée
**********
Mediainfo

General
ID                                       : 6 (0x6)
Complete name                            : /Volumes/USB 128G/ALIDVRS2/[TS]2017-04-02.20.51.09-TF1-84/000.ts
Format                                   : MPEG-TS
File size                                : 3.81 GiB
Duration                                 : 2 h 8 min
Start time                               : UTC 2017-04-02 18:51:19
End time                                 : UTC 2017-04-02 20:59:52
Overall bit rate mode                    : Variable
Overall bit rate                         : 4 241 kb/s
Network name                             : F
Country                                  : FRA
Timezone                                 : +02:00:00

Video
ID                                       : 120 (0x78)
Menu ID                                  : 1537 (0x601)
Format                                   : AVC
Format/Info                              : Advanced Video Codec
Format profile                           : High@L4
Format settings, CABAC                   : Yes
Format settings, ReFrames                : 4 frames
Codec ID                                 : 27
Duration                                 : 2 h 8 min
Bit rate                                 : 3 676 kb/s
Width                                    : 1 920 pixels
Height                                   : 1 080 pixels
Display aspect ratio                     : 16:9
Frame rate                               : 25.000 FPS
Standard                                 : Component
Color space                              : YUV
Chroma subsampling                       : 4:2:0
Bit depth                                : 8 bits
Scan type                                : MBAFF
Scan type, store method                  : Interleaved fields
Scan order                               : Top Field First
Bits/(Pixel*Frame)                       : 0.071
Stream size                              : 3.31 GiB (87%)
Color range                              : Limited
Color primaries                          : BT.709
Transfer characteristics                 : BT.709
Matrix coefficients                      : BT.709

Audio #1
ID                                       : 130 (0x82)
Menu ID                                  : 1537 (0x601)
Format                                   : E-AC-3
Format/Info                              : Enhanced Audio Coding 3
Format settings, Endianness              : Big
Codec ID                                 : 6
Duration                                 : 2 h 8 min
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 187.500 FPS (256 spf)
Compression mode                         : Lossy
Delay relative to video                  : -528 ms
Stream size                              : 118 MiB (3%)
Language                                 : French
Service kind                             : Complete Main

Audio #2
ID                                       : 131 (0x83)
Menu ID                                  : 1537 (0x601)
Format                                   : E-AC-3
Format/Info                              : Enhanced Audio Coding 3
Format settings, Endianness              : Big
Codec ID                                 : 6
Duration                                 : 2 h 8 min
Bit rate mode                            : Constant
Bit rate                                 : 128 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 187.500 FPS (256 spf)
Compression mode                         : Lossy
Delay relative to video                  : -528 ms
Stream size                              : 118 MiB (3%)
Language                                 : qaa
Service kind                             : Complete Main

Audio #3
ID                                       : 132 (0x84)
Menu ID                                  : 1537 (0x601)
Format                                   : E-AC-3
Format/Info                              : Enhanced Audio Coding 3
Format settings, Endianness              : Big
Codec ID                                 : 6
Duration                                 : 2 h 8 min
Bit rate mode                            : Constant
Bit rate                                 : 96.0 kb/s
Channel(s)                               : 2 channels
Channel positions                        : Front: L R
Sampling rate                            : 48.0 kHz
Frame rate                               : 187.500 FPS (256 spf)
Compression mode                         : Lossy
Delay relative to video                  : -464 ms
Stream size                              : 88.4 MiB (2%)
Language                                 : qad
Service kind                             : Complete Main

Text #1
ID                                       : 150 (0x96)
Menu ID                                  : 1537 (0x601)
Format                                   : DVB Subtitle
Codec ID                                 : 6
Language                                 : French

Text #2
ID                                       : 151 (0x97)
Menu ID                                  : 1537 (0x601)
Format                                   : DVB Subtitle
Codec ID                                 : 6
Language                                 : French

**Comment by lelegard** [comment]
Thank you for the report. 
Switching to French to adapt to the original report, sorry for potential readers.

Pour analyser le problème, il faudrait que j'ai accès au fichier enregistrement, ou au moins à un extrait de quelques minutes. Avez-vous la possibilité de le partager sur un site quelconque? Peut-être dl.free.fr. Quitte à le supprimer ensuite pour faire de la place.

Sinon, quelle est la version de QtlMovie, ffmpeg ("About Media Tools") et le système (Windows, Mac)?

Et merci pour le "merci".

EDIT: Vu le nom de fichier, ça doit être un Mac...

**Comment by pleiade67** [comment]
Bonjour et merci pour ce retour très rapide,
version de Qtlmovie : Version 1.11 (Nov 11 2016)
ffmpeg version N-81124-g77eb05a-tessus Copyright (c) 2000-2016 the FFmpeg developers
Mac OSX 10.10.5
Les fichiers dont je dispose font plusieurs GO. Pour que ce ne soit pas trop long à charger, je vais enregistrer qqs mns ce soir et vous les mettrai à disposition sur dl.free.
(Et encore merci : cela faisait très longtemps que je cherchais un logiciel capable de gérer correctement les flux freebox et TNT **avec** les sous-titres !)

**Comment by pleiade67** [comment]
Voici un lien vers un fichier de 5 mn environ (flux TNT FR3 HD, avec deux flux de sous-titres, qui s'affichent sous VLC). 
https://www.dropbox.com/s/out2yp1gszrr1bf/000.ts?dl=1
Merci !

**Comment by lelegard** [comment]
J'ai récupéré le fichier et constaté le problème. Je vais essayer d'investiguer ce week-end.

**Comment by lelegard** [comment]
The problem is fixed in pre-release 1.12-rc3. You may test it using the following link:
https://sourceforge.net/projects/qtlmovie/files/test/QtlMovie-1.12-rc3.dmg/download

**Comment by pleiade67** [comment]
Thank you so much !

I have tested the new version on :
- french TNT recordings (recorder: CGV ETIMO T2 REC) (DVB-T H264) with DVB subs : works 
- german DVB-T2 HEVC=H265 (recorder: CGV ETIMO T2 REC) with teletext subs : works !
To my best knowledge this is the only soft that manages DVB-T H264 HD and DVB-T2 HEVC streams with subs (and without video-audio-out of sync problems)  (already tested : handbrake, videomonkey that do not work properly).
Congrats !
