### ISSUE TITLE
Is Windows XP supported ?

### ISSUE THREAD

**Issue by aismike** [qtlmovie/qtlmovie#9]
Tried the stand-alone version, biut running the .exe immediately gives me an error window
with a message similar to this: 

Impossible to find entry point Direct3DCreate9Ex in dynamic library d3d9.dll .

I'm running Windows XP Service Pack 3 : is this OS supported ?

**Comment by lelegard** [comment]
Hello,

No, Windows XP is not supported in the sense I do not have any XP system anymore and cannot test it or try to make it work in any way. QtlMovie has been tested on Windows 7 and 10 only.

QtlMovie is based on the Qt framework. The message you indicate looks like a dependency issue from Qt. And if you look at the [Qt support page](http://doc.qt.io/qt-5/supported-platforms.html), the oldest supported Windows version is 7.

So, sorry, no Windows XP or Vista.

**Comment by aismike** [comment]
Thanks for your prompt reply. It may be useful to specify this OS requirement in the description page for the Windows version, since there are still many PC's running under XP in use around the world, utilized for personal tasks like these.
Thanks for your work.

**Comment by lelegard** [comment]
The Windows requirement has been updated [here](http://qtlmovie.sourceforge.net/doc/qtlmovie-user.html#windows)
